### PR TITLE
fix: requirements for run_demo.sh

### PR DESCRIPTION
**Pull request by bottledmind**
Added scipy and scikit-image as dependencies. Solves https://github.com/salesforce/LAVIS/issues/12

### CODE REVIEW

**Comment by bottledmind** [comment]
I had an error while signing, Now I'm getting "You already signed the CLA on 2022-10-05"

**Comment by dxli94** [comment]
@bottledmind Thanks for the contribution.

I can confirm this issue. On my side, installing scikit-image is sufficient. No need to install scipy. Can you help confirm?

Thanks.

**Comment by bottledmind** [comment]
Thanks for your responce, @dxli94. 
If you want to shorten the requirements file, I've managed to launch demo with:
```
decord>=0.6.0
einops>=0.4.1
fairscale==0.4.4
iopath
omegaconf>=2.1.2
opencv-python>=4.5.5
opendatasets
plotly
pre-commit
pycocoevalcap
python-magic
scikit-image
streamlit
timm==0.4.12
torch==1.10.0
torchvision==0.11.1
transformers>=4.15.0,<4.22.0
webdataset
```
- Didn't find any usage for `contexttimer` and `ipython`. 
- The `wheel` package is a part of Python. 
- Some other packages were already included into other packages' requirements. 
Also, the file may be reduced even more: 
- `fairscale-0.4.4` has `torch >= 1.8.0`
- `transformers-4.21.3` has `fairscale>0.3`, `torch>=1.0,<1.12` and `timm`

**Comment by dxli94** [comment]
Hi @bottledmind ,

Thanks for looking into this. We've noted this down.

Kindly please just add scikit-image as the additional dependency.

We'll look into others later.

Thanks, again.

**Comment by bottledmind** [comment]
Done

**Comment by bottledmind** [comment]
I also want to appreciate your kind language, @dxli94

**Comment by dxli94** [comment]
Merged. Thanks for your contribution.

**Pull request merged**
